# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\"\xf0\x01\n\x0fInventoryRecord\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x12\n\nunit_price\x18\x04 \x01(\x01\x12\x19\n\x11quantity_in_stock\x18\x05 \x01(\x05\x12\x17\n\x0finventory_value\x18\x06 \x01(\x01\x12\x15\n\rreorder_level\x18\x07 \x01(\x05\x12\x1c\n\x14reorder_time_in_days\x18\x08 \x01(\x05\x12\x1b\n\x13quantity_in_reorder\x18\t \x01(\x05\x12\x14\n\x0c\x64iscontinued\x18\n \x01(\x08\"\x1e\n\x10InventoryRequest\x12\n\n\x02id\x18\x01 \x01(\t\"Z\n\x16InventorySearchRequest\x12\x10\n\x08key_name\x18\x01 \x01(\t\x12\x17\n\x0fkey_value_start\x18\x02 \x01(\t\x12\x15\n\rkey_value_end\x18\x03 \x01(\t\"#\n\x12PercentileResponse\x12\r\n\x05value\x18\x01 \x01(\x01\"[\n\rUpdateRequest\x12\x10\n\x08key_name\x18\x01 \x01(\t\x12\x11\n\tkey_value\x18\x02 \x01(\t\x12\x10\n\x08val_name\x18\x03 \x01(\t\x12\x13\n\x0bval_val_new\x18\x04 \x01(\t\"!\n\x0eUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xe0\x01\n\x10InventoryService\x12\x31\n\nsearchByID\x12\x11.InventoryRequest\x1a\x10.InventoryRecord\x12\x33\n\x06search\x12\x17.InventorySearchRequest\x1a\x10.InventoryRecord\x12\x39\n\x0fgetDistribution\x12\x11.InventoryRequest\x1a\x13.PercentileResponse\x12)\n\x06update\x12\x0e.UpdateRequest\x1a\x0f.UpdateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INVENTORYRECORD']._serialized_start=20
  _globals['_INVENTORYRECORD']._serialized_end=260
  _globals['_INVENTORYREQUEST']._serialized_start=262
  _globals['_INVENTORYREQUEST']._serialized_end=292
  _globals['_INVENTORYSEARCHREQUEST']._serialized_start=294
  _globals['_INVENTORYSEARCHREQUEST']._serialized_end=384
  _globals['_PERCENTILERESPONSE']._serialized_start=386
  _globals['_PERCENTILERESPONSE']._serialized_end=421
  _globals['_UPDATEREQUEST']._serialized_start=423
  _globals['_UPDATEREQUEST']._serialized_end=514
  _globals['_UPDATERESPONSE']._serialized_start=516
  _globals['_UPDATERESPONSE']._serialized_end=549
  _globals['_INVENTORYSERVICE']._serialized_start=552
  _globals['_INVENTORYSERVICE']._serialized_end=776
# @@protoc_insertion_point(module_scope)
